# Generated by Django 5.0 on 2023-12-27 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_remove_booking_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='first_name',
            new_name='name',
        ),
    ]
